### ISSUE TITLE
NEWS : pas les bons détails

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#175]
Il y a des choses étranges avec news : tous les éléments de la page http://www.elysee.ch/expositions-et-evenements/expositions-au-musee/precedentes/ renvoient sur un détail qui n'est pas correct. 

Les infos sur le détail sont incorrectes, mais l'URL semble juste. 

Vue du détail qui s'affiche pour toutes les expos précédentes.
![capture d ecran 2015-07-23 a 11 08 58](https://cloud.githubusercontent.com/assets/9978840/8847011/5f9c818a-312b-11e5-967c-df5277fa5000.png)

@jlthirot à comparer avec #172

**Comment by elyseelab** [comment]
@jlthirot ça veut dire quoi des URL qui finissent en ?from=groupmessage&isappinstalled=0

Comme par exemple elysee.ch/en/the-museum/pole-museal-future-museum/?from=groupmessage&isappinstalled=0

J'ai trouvé ça dans google analytics.

**Comment by jlthirot** [comment]
@elyseelab 
Intéressant, je pense que des applications/OS mobiles ajoutent des paramètres aux URL pour optimiser la navigation.

**Comment by alienlebarge** [comment]
A priori, cela vient de l'application [WeeChat](http://www.wechat.com/en/) qui rajoute ces variables à la fin des URLs.

> When opening a webpage, WeChat adds `isappinstalled` to the original URL, that is, `http://xxxx/?isappinstalled=[1|0]`. `1` means Installed and `0` means Not-installed.
> - [WeChat Support](http://dev.wechat.com/support)

WeChat est une application de messagerie (idem WhatsApp) très utilisé en Chine.

**Comment by elyseelab** [comment]
Ca me semble cohérent, on a eu pas mal d'échanges avec la Chine la semaine passée.

**Comment by jlthirot** [comment]
@elyseelab 
Je ferme le cas
