### ISSUE TITLE
Impossible d'attribuer les cas

### ISSUE THREAD

**Issue by alienlebarge** [DSI-VD/elyseech#184]
Question de @elyseelab

> PS : Je peux plus attribuer les cas à qui que ce soit

**Comment by alienlebarge** [comment]
J'ai créé un groupe nommée "Elysée". @elyseelab, je t'ai envoyé un invite. Cela devrait te redonner le droit d'attribuer les cas.

**Comment by alienlebarge** [comment]
@elyseelab est-ce que c'est bon pour toi ?
D'après mes tests ça a l'air pas mal.
Si ok, tu peux fermer le cas

**Comment by elyseelab** [comment]
@alienlebarge ben ça marche pas, si je crée une issue, j'ai pas les labels, Milestone et Assignee

**Comment by alienlebarge** [comment]
J'ai donné au groupe Elysée les droits "Write" sur le repo.

@elyseelab, est-ce que tu peux retester ?

**Comment by elyseelab** [comment]
@alienlebarge ça marche j'ai testé sur qq issues. Merci

**Comment by alienlebarge** [comment]
:tada:

**Comment by alienlebarge** [comment]
@elyseelab est-ce que tu peux me dire si tu peux toujours assigner de cas ?
Étant la seule personne non DIS sur le GitHub pour l'instant, tu sers un peu de cobaye. Désolé.

**Comment by elyseelab** [comment]
@alienlebarge ben alors j'ai plus aucun droit de modification sur 
*Labels
*Milestone
*Assignee

**Comment by alienlebarge** [comment]
Je t'ai remise les droits *Write*. Est-ce que cela a réglé le problème ?

**Comment by elyseelab** [comment]
@alienlebarge oui ça marche merci

**Comment by alienlebarge** [comment]
:tada:
