### ISSUE TITLE
Agenda : l'agenda n'affiche pas les événements du jour en cours

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#186]
L'agenda (http://www.elysee.ch/no_cache/expositions-et-evenements/agenda/) n'affiche pas les événements d'aujourd'hui (6 oct). On dirait que les événements disparaissent dès la date de début. 

Il me semble qu'on avait déjà vu ça, c'est possible @jlthirot ?

**Comment by elyseelab** [comment]
En l’occurrence il s'agit des actu id=4008 et id=4009 qui devraient être affichés.

**Comment by jlthirot** [comment]
@elyseelab 

C'est corrigé pour agenda home, agenda list, agenda 2 prochains évènements.
Le filtre sur les dates n'était pas très correct.
est-ce ok ?
J'ai caché le test

´´´´
# do not use startdate 
# news.tx_roqnewsevent_startdate >= {strtotime:now}
# use today
news.tx_roqnewsevent_enddate >= {strtotime:today}
´´´´

**Comment by elyseelab** [comment]
@jlthirot oui c'est OK. J'ai testé sur 
- Homepage
- [Liste agenda](http://www.elysee.ch/no_cache/expositions-et-evenements/agenda/)
- Tesseract sur [page avec layout expo](http://www.elysee.ch/expositions-et-evenements/expositions/la-memoire-des-images/)
Tests sur FR + EN
