### ISSUE TITLE
Backend : Editer une colonne

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#190]
Lorsque je veux éditer une colonne, j'ai une erreur lorsque j'enregistre : "La validation du jeton de sécurité a échoué. Recharger le formulaire et envoyez le à nouveau". 
Impossible d'enregistrer les modifications du coup. 

<img width="781" alt="capture d ecran 2015-10-12 a 11 48 24" src="https://cloud.githubusercontent.com/assets/9978840/10425376/8998b4cc-70d7-11e5-9427-eb3162f8423c.png">

**Comment by jlthirot** [comment]
@elyseelab 
Ca arrive de temps en temps. Il faut recharger la page.

**Comment by elyseelab** [comment]
OK merci
