### ISSUE TITLE
Footer : infos tél + adresse EN

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#191]
Sur le footer en EN, les info téléphone + adresse passent sur 2 lignes (en FR c'est OK).
Les infos du footer sont modifiables depuis id=7076
Ca a peut-être changé après ma dernière modification du contenu du footer gauche.

<img width="488" alt="capture d ecran 2015-10-12 a 12 26 44" src="https://cloud.githubusercontent.com/assets/9978840/10426283/dc7d133e-70de-11e5-992a-7d6dc30f8ae3.png">

**Comment by jlthirot** [comment]
@elyseelab 
Je ne trouve pas le footer sur la page 7076
@alienlebarge 
le css est faux, chaque div est impacté
".mel_module_footer .col_right div "

**Comment by elyseelab** [comment]
@jlthirot pardon j'ai fait une faute frappe : dans le backend, il faut aller sur id=7067 (liens pied de page).

**Comment by jlthirot** [comment]
@elyseelab, @alienlebarge,  
J'ai finalement corrigé le css.

**Comment by elyseelab** [comment]
@jlthirot merci c'est tout bon
