### ISSUE TITLE
mel_module_slider_expos_paralelle

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#192]
Le module qui doit afficher les expos en parallèle sur les pages avec template Expo Detail Layout a un comportement étrange :
- Si date > aujourd'hui ça marche
- Si date = aujourd'hui ça marche pas
- Si date < aujourd'hui ça marche pas

**Le module est celui-ci**
<img width="1328" alt="capture d ecran 2015-10-12 a 15 17 04" src="https://cloud.githubusercontent.com/assets/9978840/10428874/c0033d80-70f4-11e5-93ad-41a62b98e441.png">

**Comportement souhaité :**
Le module doit afficher les titres des expos qui sont en même temps que l'expo sur la page. Ces liens sont toujours les mêmes, ils ne varient pas avec le temps. 
Le module se masque si il n'y a rien a afficher.

**Exemple :**
Expo X a lieu du 7.10.2015 au 10.2.2016
Expo Y a lieu du 1.10.2015 au 15.1.2016

Sur la page Expo X le module doit afficher le lien de Expo Y (tout le temps, même si l'expo X ou Y est finie). 
Sur la page Expo Y, le module doit afficher le lien de Expo X tout le temps, même si l'expo X ou Y est finie). 

**Sélection de la plage de dates**
Pour indiquer la plage de dates à utiliser, il faut renseigner l'actu correspondant à l'expo (actualité qui pointe sur cette page) dans l'onglet Musée de l'Elysée des propriétés de la page.
<img width="927" alt="capture d ecran 2015-10-12 a 15 15 46" src="https://cloud.githubusercontent.com/assets/9978840/10428889/d09f389c-70f4-11e5-8b32-8644a87e1335.png">

**Comment by elyseelab** [comment]
cf #84

**Comment by jlthirot** [comment]
@elyseelab 
Je ne trouve pas l'expo de la copie d'écran. C'est quelle page ?

**Comment by jlthirot** [comment]
NOTES
----------

# Category : Expositions
# catégorie Exposition au musée
#categorylist andgroup 35
categorylist andgroup 5

pages.uid = tsfe:id



SELECT
news.*,
media.*,
categories.uid,
categories.title,
categories.parentcategory,
news. tx_roqnewsevent_location AS categories.location,
CONCAT_WS(',', categories.uid, categories.parentcategory) AS categorylist
FROM tx_news_domain_model_news AS news

INNER JOIN tx_news_domain_model_news AS relatedexpo
ON (
	(news.tx_roqnewsevent_startdate < relatedexpo.tx_roqnewsevent_enddate
	AND news.tx_roqnewsevent_startdate > relatedexpo.tx_roqnewsevent_startdate)
	OR
	(news.tx_roqnewsevent_enddate < relatedexpo.tx_roqnewsevent_enddate
	AND news.tx_roqnewsevent_enddate > relatedexpo.tx_roqnewsevent_startdate)
)

INNER JOIN pages
ON pages.tx_vdtmplelysee_related_news = relatedexpo.uid

INNER JOIN tx_news_domain_model_news_category_mm AS elysee_category
ON elysee_category.uid_local = news.uid
AND elysee_category.uid_foreign = 27

LEFT JOIN tx_news_domain_model_news_category_mm
ON tx_news_domain_model_news_category_mm.uid_local = news.uid

LEFT JOIN tx_news_domain_model_category AS categories
ON categories.uid = tx_news_domain_model_news_category_mm.uid_foreign

LEFT JOIN tx_news_domain_model_media AS media
ON media.parent = news.uid



[  1  ] [   2  ]   [     3]   [    4    ]   [  5]

             [    2 et 4          ]

- Le cas 3 est exclu 
Il faut ajouter start O <= start R AND end O >= end R
- le category 27 correspond uniquement au groupe Musee Elysee FR. Vérifier avec l'EN
- Ajouter égalités dans les conditions
- Un filtre date now semble aplliqué selon le commentaire de Manuel

**Comment by jlthirot** [comment]
@elyseelab 
Est-ce possible d'avoir un cas concret afin de pouvoir tester.

- Selon une analyse rapide les expos ont lieu strictement en même temps
http://www.elysee.ch/index.php?id=7480 affiche aucune expo
Après la correction des égalités elle affiche 3 actus en //

Test William page 7480 news 3714 dates 30.1.2015 - 30.05.2015

**Comment by elyseelab** [comment]
@jlthirot Le cas concret est http://www.elysee.ch/index.php?id=7480
La capture d'écran est fait sur une page qui ne doit pas avoir d'expo en // (c'était pour l'exemple).

Sur William page 7480 news 3714 dates 30.1.2015 - 30.05.2015, chez moi ça n'apparait pas en fr, malgré un vidage du cache. 

Si tu dis que tu as 3 expos en // c'est qu'il y en a une de trop, il y en a que 2 à afficher. 

Pour William page 7480 news 3714 dates 30.1.2015 - 30.05.2015 il faut afficher : 
- Photobooks.Elysée news 3717
- Prix Elysée, l'exposition des nominés news 3537

**Comment by jlthirot** [comment]
@elyseelab 
En effet hier soir les expos en // ne s'affichent pas depuis chez moi.
Ce matin les 3 expos en // sont visibles depuis l'ACV et depuis mon téléphone HTC

Dans l'ordre
- Prix Elysée, l'exposition des nominés news 3537
- William Eggleston, From Black and White to Color
- Photobooks.Elysée news 3717

**Comment by jlthirot** [comment]
corrects filter
  ```
	OR
	(news.tx_roqnewsevent_startdate <= relatedexpo.tx_roqnewsevent_startdate
	AND news.tx_roqnewsevent_enddate >= relatedexpo.tx_roqnewsevent_enddate)
```

**Comment by jlthirot** [comment]
Test de la version anglaise de 
http://www.elysee.ch/en/exhibitions-and-events/expositions/william-eggleston-from-black-and-white-to-color/
est ok les 3 expo en // sont affichées

**Comment by jlthirot** [comment]
to do
 exclure la news correspondante à la page exposition 

@elyseelab 
- Est-ce une bonne idée de limiter à 2 expos en // ?

**Comment by elyseelab** [comment]
@jlthirot non il faut pas limiter à 2 en // mais juste exclure la news correspondante à la page exposition.

**Comment by jlthirot** [comment]
@elyseelab 

Exclusion de la news correspondante 
```
WHERE news.uid <> pages.tx_vdtmplelysee_related_news
````
Ok sur la page 7480 en FR et EN

**Comment by jlthirot** [comment]
@elyseelab 
Les liens sont KO
    Prix Elysée, l'exposition des nominés news 3537
    Photobooks.Elysée news 3717

**Comment by elyseelab** [comment]
@jlthirot la cible dépend de ce qui est dans l'actualité : parfois c'est une page, parfois c'est un détail. 
Mais on peut peut-être simplifier ça. 

Chez moi les liens sont vides (href="").

**Comment by jlthirot** [comment]
@elyseelab 
Je viens de vider le cache. Est-ce ok maintenant ?

**Comment by elyseelab** [comment]
@jlthirot oui ça a l'air OK.

**Comment by elyseelab** [comment]
@jlthirot pour le titre anglais du bloc (h4 - Expositions en parallèle) est-ce que tu peux mettre On view ?
Merci

**Comment by jlthirot** [comment]
@elyseelab 
Une histoire sans fin ..
C'est fait
```
On view

A single ticket gives you acces to all exhibitions at the Musée de l'Elysée.
```

**Comment by elyseelab** [comment]
@jlthirot merci bcp. Je fais encore quelques tests et je ferme le cas.

**Comment by elyseelab** [comment]
@jlthirot OK pour moi je clos.
