### ISSUE TITLE
Image border par défaut

### ISSUE THREAD

**Issue by elyseelab** [DSI-VD/elyseech#197]
Est-il possible de régler le boder des images à 1px par défaut ? 
border: 1px solid #000;

**Comment by alienlebarge** [comment]
@elyseelab, tu entend quoi par `border` ?
Mettre un `border-radius` ou un liserais de `1px` ?

http://codepen.io/alienlebarge/pen/d4c34a12ff9e692745ecdf659aa99f55/

**Comment by elyseelab** [comment]
@alienlebarge c'est un un liserais de 1px qui s'applique lorsque je coche la case Bordure dans l'onglet disposition. Par défaut, on dirait que c'est réglé sur 2px. 

<img width="999" alt="capture d ecran 2015-11-03 a 09 34 30" src="https://cloud.githubusercontent.com/assets/9978840/10903875/a29c5418-820e-11e5-9e0a-ce876b93e9f2.png">

**Comment by alienlebarge** [comment]
Je vois.

**Comment by alienlebarge** [comment]
C'est corrigé

**Comment by elyseelab** [comment]
@alienlebarge super merci !!
